// Class automatically generated by Dev-C++ New Class wizard
#include <windows.h>
#include <gl\gl.h>
#include <gl\glu.h>
#include <gl\glext.h>

#include <stdlib.h>
#include <time.h>

#ifndef CPARTICLESYSTEM_H
#define CPARTICLESYSTEM_H

// No description
class CParticleSystem
{
      
    // Function Definitions
	public:
		
    // class constructor
	CParticleSystem();
	// class destructor
	~CParticleSystem();
	
    void CParticleSystem::Activate(float xpos, float ypos, float zpos, int numparticles, int mintimetolive, int maxtimetolive);
    void CParticleSystem::Adjust();
    void CParticleSystem::Render();	
	
    float CParticleSystem::RandomFloat(float min, float max, int step);	
    int CParticleSystem::RandomInt(int min, int max);	
	
    // Storage Definitions
    
    struct PARTICLE {
           
        float x,y,z;
        float size;
        float sx,sy,sz;
        float tsx,tsy,tsz;
        float R,G,B;
        int TTL;       
           
    };
    
    
    // Variable Definitions
    
    bool ACTIVE;
       
    float x,y,z;   
    float sx,sy,sz;
    float tsx,tsy,tsz;
    int TTL;
    
    int ParticleCount;
       
    PARTICLE * Particles;  
    
	float minparticlespeed, maxparticlespeed, settsx, settsy, settsz, setsize;
	bool RANDOMCOLOUR;
	float RED,GREEN,BLUE;
	
	GLuint texture;
	
};

#endif // CPARTICLESYSTEM_H
